package Exceptions;

public class Main {

	public static void main(String[] args) {
		
		int[] werte = {23, 43, 87, 42};
		

		
		try {
		System.out.println(fehler(7));
		}
		catch(OutOfBoundsException e) {
			
		
		}
	}

	private static char[] fehler(int i) {
		// TODO Auto-generated method stub
		return null;
	}

}
